// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	na "gl-app/api/internal/handler/na"
	"gl-app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// captcha
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: na.CaptchaHandler(serverCtx),
			},
			{
				// login
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: na.LoginHandler(serverCtx),
			},
			{
				// register
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: na.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/na/v1"),
	)
}
