// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	app "gl-app/api/internal/handler/app"
	media "gl-app/api/internal/handler/media"
	na "gl-app/api/internal/handler/na"
	"gl-app/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// App首页推荐作品列表
				Method:  http.MethodGet,
				Path:    "/recommend/works",
				Handler: app.GetRecommendWorkListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/app/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询审核中心作品列表
				Method:  http.MethodGet,
				Path:    "/audit/works",
				Handler: media.GetAuditWorkListHandler(serverCtx),
			},
			{
				// 查询审核作品详情
				Method:  http.MethodGet,
				Path:    "/audit/works/:workId",
				Handler: media.GetAuditWorkDetailHandler(serverCtx),
			},
			{
				// 动态生成审核作品HLS播放清单
				Method:  http.MethodGet,
				Path:    "/audit/works/:workId/playlist",
				Handler: media.GetAuditWorkPlaylistHandler(serverCtx),
			},
			{
				// 查询当前用户所有处理完成的作品
				Method:  http.MethodGet,
				Path:    "/creator/works",
				Handler: media.GetCreatorWorkListHandler(serverCtx),
			},
			{
				// 删除当前用户作品
				Method:  http.MethodDelete,
				Path:    "/creator/works/:workId",
				Handler: media.DeleteCreatorWorkHandler(serverCtx),
			},
			{
				// 修改当前用户作品标题
				Method:  http.MethodPut,
				Path:    "/creator/works/:workId/title",
				Handler: media.UpdateCreatorWorkTitleHandler(serverCtx),
			},
			{
				// 修改当前用户作品可见性
				Method:  http.MethodPut,
				Path:    "/creator/works/:workId/visibility",
				Handler: media.UpdateCreatorWorkVisibilityHandler(serverCtx),
			},
			{
				// 检查文件是否上传完成
				Method:  http.MethodPost,
				Path:    "/media/upload/complete",
				Handler: media.CompleteUploadHandler(serverCtx),
			},
			{
				// 创建预签地址
				Method:  http.MethodPost,
				Path:    "/media/upload/presign",
				Handler: media.CreateUploadPresignHandler(serverCtx),
			},
			{
				// 创建作品并提交媒体处理
				Method:  http.MethodPost,
				Path:    "/works",
				Handler: media.CreateWorkHandler(serverCtx),
			},
			{
				// 查询作品详情
				Method:  http.MethodGet,
				Path:    "/works/:workId",
				Handler: media.GetWorkHandler(serverCtx),
			},
			{
				// 审核作品
				Method:  http.MethodPost,
				Path:    "/works/:workId/audit",
				Handler: media.AuditWorkHandler(serverCtx),
			},
			{
				// 动态生成作品HLS播放清单
				Method:  http.MethodGet,
				Path:    "/works/:workId/playlist",
				Handler: media.GetWorkPlaylistHandler(serverCtx),
			},
			{
				// 重试失败的媒体处理任务
				Method:  http.MethodPost,
				Path:    "/works/:workId/retry",
				Handler: media.RetryWorkHandler(serverCtx),
			},
			{
				// 查询作品媒体处理、审核和发布状态
				Method:  http.MethodGet,
				Path:    "/works/:workId/status",
				Handler: media.GetWorkStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 图片验证码
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: na.CaptchaHandler(serverCtx),
			},
			{
				// 登录接口
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: na.LoginHandler(serverCtx),
			},
			{
				// 注册接口
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: na.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/na/v1"),
	)
}
