// Code generated by goctl. DO NOT EDIT.

package media

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaAssetFieldNames          = builder.RawFieldNames(&MediaAsset{})
	mediaAssetRows                = strings.Join(mediaAssetFieldNames, ",")
	mediaAssetRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaAssetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaAssetRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaAssetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMediaAssetIdPrefix        = "cache:mediaAsset:id:"
	cacheMediaAssetObjectKeyPrefix = "cache:mediaAsset:objectKey:"
)

type (
	mediaAssetModel interface {
		Insert(ctx context.Context, data *MediaAsset) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MediaAsset, error)
		FindOneByObjectKey(ctx context.Context, objectKey string) (*MediaAsset, error)
		Update(ctx context.Context, data *MediaAsset) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMediaAssetModel struct {
		sqlc.CachedConn
		table string
	}

	MediaAsset struct {
		Id           int64        `db:"id"`            // 主键自增ID
		CreatedAt    time.Time    `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time    `db:"updated_at"`    // 更新时间
		DeletedAt    sql.NullTime `db:"deleted_at"`    // 软删除标记
		UserId       int64        `db:"user_id"`       // 上传用户ID
		ResourceType string       `db:"resource_type"` // 资源类型: image/video
		Bucket       string       `db:"bucket"`        // 对象存储桶
		ObjectKey    string       `db:"object_key"`    // 对象存储路径
		OriginName   string       `db:"origin_name"`   // 原始文件名
		ContentType  string       `db:"content_type"`  // 文件MIME类型
		Ext          string       `db:"ext"`           // 文件扩展名
		FileSize     int64        `db:"file_size"`     // 对象存储中的文件大小
		Status       string       `db:"status"`        // 上传状态: uploading/uploaded/failed
	}
)

func newMediaAssetModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMediaAssetModel {
	return &defaultMediaAssetModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`media_asset`",
	}
}

func (m *defaultMediaAssetModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mediaAssetIdKey := fmt.Sprintf("%s%v", cacheMediaAssetIdPrefix, id)
	mediaAssetObjectKeyKey := fmt.Sprintf("%s%v", cacheMediaAssetObjectKeyPrefix, data.ObjectKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mediaAssetIdKey, mediaAssetObjectKeyKey)
	return err
}

func (m *defaultMediaAssetModel) FindOne(ctx context.Context, id int64) (*MediaAsset, error) {
	mediaAssetIdKey := fmt.Sprintf("%s%v", cacheMediaAssetIdPrefix, id)
	var resp MediaAsset
	err := m.QueryRowCtx(ctx, &resp, mediaAssetIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaAssetRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaAssetModel) FindOneByObjectKey(ctx context.Context, objectKey string) (*MediaAsset, error) {
	mediaAssetObjectKeyKey := fmt.Sprintf("%s%v", cacheMediaAssetObjectKeyPrefix, objectKey)
	var resp MediaAsset
	err := m.QueryRowIndexCtx(ctx, &resp, mediaAssetObjectKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `object_key` = ? limit 1", mediaAssetRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, objectKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaAssetModel) Insert(ctx context.Context, data *MediaAsset) (sql.Result, error) {
	mediaAssetIdKey := fmt.Sprintf("%s%v", cacheMediaAssetIdPrefix, data.Id)
	mediaAssetObjectKeyKey := fmt.Sprintf("%s%v", cacheMediaAssetObjectKeyPrefix, data.ObjectKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, mediaAssetRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.ResourceType, data.Bucket, data.ObjectKey, data.OriginName, data.ContentType, data.Ext, data.FileSize, data.Status)
	}, mediaAssetIdKey, mediaAssetObjectKeyKey)
	return ret, err
}

func (m *defaultMediaAssetModel) Update(ctx context.Context, newData *MediaAsset) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mediaAssetIdKey := fmt.Sprintf("%s%v", cacheMediaAssetIdPrefix, data.Id)
	mediaAssetObjectKeyKey := fmt.Sprintf("%s%v", cacheMediaAssetObjectKeyPrefix, data.ObjectKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaAssetRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeletedAt, newData.UserId, newData.ResourceType, newData.Bucket, newData.ObjectKey, newData.OriginName, newData.ContentType, newData.Ext, newData.FileSize, newData.Status, newData.Id)
	}, mediaAssetIdKey, mediaAssetObjectKeyKey)
	return err
}

func (m *defaultMediaAssetModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMediaAssetIdPrefix, primary)
}

func (m *defaultMediaAssetModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaAssetRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMediaAssetModel) tableName() string {
	return m.table
}
