// Code generated by goctl. DO NOT EDIT.
package types

type AppUserProfileReq struct {
	UserId int64 `path:"userId"`
}

type AppUserProfileResp struct {
	UserId    int64  `json:"userId"`
	NickName  string `json:"nickName"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type AppWorkAssetItem struct {
	MediaId int64  `json:"mediaId"`
	Role    string `json:"role"`
	Sort    int64  `json:"sort"`
	Url     string `json:"url"`
	Width   int64  `json:"width"`
	Height  int64  `json:"height"`
}

type AppWorkDetailReq struct {
	WorkId int64 `path:"workId"`
}

type AppWorkDetailResp struct {
	WorkId        int64               `json:"workId"`
	Type          string              `json:"type"`
	Title         string              `json:"title"`
	Content       string              `json:"content"`
	CoverUrl      string              `json:"coverUrl"`
	DurationMs    int64               `json:"durationMs"`
	VideoPlaylist string              `json:"videoPlaylist,optional"`
	PublishedAt   string              `json:"publishedAt"`
	Author        RecommendAuthorItem `json:"author"`
	Like          RecommendLikeInfo   `json:"like"`
	FavoriteCount int64               `json:"favoriteCount"`
	CommentCount  int64               `json:"commentCount"`
	ShareCount    int64               `json:"shareCount"`
	Assets        []AppWorkAssetItem  `json:"assets"`
	Topics        []AppWorkTopicItem  `json:"topics"`
}

type AppWorkTopicItem struct {
	TopicId int64  `json:"topicId"`
	Name    string `json:"name"`
}

type AuditWorkDetailResp struct {
	WorkId        int64           `json:"workId"`
	Type          string          `json:"type"`
	Title         string          `json:"title"`
	Content       string          `json:"content"`
	CoverUrl      string          `json:"coverUrl"`
	DurationMs    int64           `json:"durationMs"`
	VideoPlaylist string          `json:"videoPlaylist,optional"`
	Visibility    string          `json:"visibility"`
	Original      bool            `json:"original"`
	AuthorId      int64           `json:"authorId"`
	AuthorName    string          `json:"authorName"`
	AuthorEmail   string          `json:"authorEmail"`
	ReviewStatus  string          `json:"reviewStatus"`
	PublishStatus string          `json:"publishStatus"`
	ReviewReason  string          `json:"reviewReason,optional"`
	ScheduledAt   string          `json:"scheduledAt,optional"`
	SubmittedAt   string          `json:"submittedAt"`
	ReviewedAt    string          `json:"reviewedAt,optional"`
	Assets        []WorkAssetItem `json:"assets"`
	Topics        []WorkTopicItem `json:"topics"`
}

type AuditWorkListItem struct {
	WorkId         int64  `json:"workId"`
	Type           string `json:"type"`
	Title          string `json:"title"`
	ContentExcerpt string `json:"contentExcerpt"`
	CoverUrl       string `json:"coverUrl"`
	DurationMs     int64  `json:"durationMs"`
	Visibility     string `json:"visibility"`
	AuthorId       int64  `json:"authorId"`
	AuthorName     string `json:"authorName"`
	ReviewStatus   string `json:"reviewStatus"`
	PublishStatus  string `json:"publishStatus"`
	ReviewReason   string `json:"reviewReason,optional"`
	SubmittedAt    string `json:"submittedAt"`
	ReviewedAt     string `json:"reviewedAt,optional"`
}

type AuditWorkListReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
	Type     string `form:"type,optional"`
	Keyword  string `form:"keyword,optional"`
}

type AuditWorkListResp struct {
	Total         int64               `json:"total"`
	Page          int64               `json:"page"`
	PageSize      int64               `json:"pageSize"`
	PendingCount  int64               `json:"pendingCount"`
	ApprovedCount int64               `json:"approvedCount"`
	RejectedCount int64               `json:"rejectedCount"`
	List          []AuditWorkListItem `json:"list"`
}

type AuditWorkReq struct {
	WorkId   int64  `path:"workId"`
	Decision string `json:"decision"`
	Reason   string `json:"reason,optional"`
}

type AuditWorkResp struct {
	WorkId        int64  `json:"workId"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
}

type CaptchaResp struct {
	CaptchaID   string `json:"captchaId"`
	CaptchaPath string `json:"captchaPath"`
}

type CompleteUploadReq struct {
	MediaId   int64  `json:"mediaId"`
	ObjectKey string `json:"objectKey"`
}

type CompleteUploadResp struct {
	MediaId    int64  `json:"mediaId"`
	Status     string `json:"status"`
	Bucket     string `json:"bucket"`
	ObjectKey  string `json:"objectKey"`
	PreviewUrl string `json:"previewUrl"`
}

type CreateUploadPresignReq struct {
	ResourceType string `json:"resourceType"`
	FileName     string `json:"fileName"`
	ContentType  string `json:"contentType,optional"`
}

type CreateUploadPresignResp struct {
	MediaId    int64             `json:"mediaId"`
	Bucket     string            `json:"bucket"`
	ObjectKey  string            `json:"objectKey"`
	UploadUrl  string            `json:"uploadUrl"`
	PreviewUrl string            `json:"previewUrl"`
	Method     string            `json:"method"`
	ExpiresIn  int64             `json:"expiresIn"`
	Headers    map[string]string `json:"headers"`
}

type CreateWorkReq struct {
	Payload string `form:"payload"`
}

type CreateWorkResp struct {
	WorkId        int64  `json:"workId"`
	ProcessStatus string `json:"processStatus"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
}

type CreatorWorkListItem struct {
	WorkId        int64  `json:"workId"`
	Type          string `json:"type"`
	Title         string `json:"title"`
	CoverUrl      string `json:"coverUrl"`
	DurationMs    int64  `json:"durationMs"`
	Visibility    string `json:"visibility"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
	ReviewReason  string `json:"reviewReason,optional"`
	ScheduledAt   string `json:"scheduledAt,optional"`
	PublishedAt   string `json:"publishedAt,optional"`
	CreatedAt     string `json:"createdAt"`
}

type CreatorWorkListReq struct {
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
	Status   string `form:"status,optional"`
	Keyword  string `form:"keyword,optional"`
}

type CreatorWorkListResp struct {
	Total          int64                 `json:"total"`
	Page           int64                 `json:"page"`
	PageSize       int64                 `json:"pageSize"`
	AllCount       int64                 `json:"allCount"`
	PublishedCount int64                 `json:"publishedCount"`
	ReviewingCount int64                 `json:"reviewingCount"`
	RejectedCount  int64                 `json:"rejectedCount"`
	List           []CreatorWorkListItem `json:"list"`
}

type CreatorWorkMutationResp struct {
	WorkId  int64 `json:"workId"`
	Updated bool  `json:"updated"`
}

type LoginReq struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	CaptchaID   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserId       int64  `json:"userId"`
	NickName     string `json:"nickName"`
	AvatarUrl    string `json:"avatarUrl,optional"`
}

type RecommendAuthorItem struct {
	UserId    int64  `json:"userId"`
	NickName  string `json:"nickName"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type RecommendLikeInfo struct {
	Liked bool   `json:"liked"`
	Count int64  `json:"count"`
	Text  string `json:"text"`
}

type RecommendWorkItem struct {
	WorkId         int64               `json:"workId"`
	Type           string              `json:"type"`
	Title          string              `json:"title"`
	ContentExcerpt string              `json:"contentExcerpt"`
	CoverUrl       string              `json:"coverUrl"`
	DurationMs     int64               `json:"durationMs"`
	PublishedAt    string              `json:"publishedAt"`
	Author         RecommendAuthorItem `json:"author"`
	Like           RecommendLikeInfo   `json:"like"`
}

type RecommendWorkListReq struct {
	UserID   int64 `form:"userId"`
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type RecommendWorkListResp struct {
	Page     int64               `json:"page"`
	PageSize int64               `json:"pageSize"`
	HasMore  bool                `json:"hasMore"`
	List     []RecommendWorkItem `json:"list"`
}

type RegisterReq struct {
	Email            string `json:"email"`
	NickName         string `json:"nickName"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UpdateCreatorWorkTitleReq struct {
	WorkId int64  `path:"workId"`
	Title  string `json:"title"`
}

type UpdateCreatorWorkVisibilityReq struct {
	WorkId     int64  `path:"workId"`
	Visibility string `json:"visibility"`
}

type UpdateUserInfoReq struct {
}

type UpdateUserProfileReq struct {
	NickName string `json:"nickName"`
}

type UploadUserAvatarReq struct {
}

type User struct {
	Id       int64  `json:"id"`
	Email    string `json:"email"`
	NickName string `json:"nickName"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
}

type UserProfileResp struct {
	UserId    int64  `json:"userId"`
	Email     string `json:"email"`
	NickName  string `json:"nickName"`
	AvatarUrl string `json:"avatarUrl,optional"`
}

type UserPublishedWorkListReq struct {
	UserId   int64 `path:"userId"`
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type UserPublishedWorkListResp struct {
	Total    int64               `json:"total"`
	Page     int64               `json:"page"`
	PageSize int64               `json:"pageSize"`
	HasMore  bool                `json:"hasMore"`
	List     []RecommendWorkItem `json:"list"`
}

type WorkAssetItem struct {
	MediaId int64  `json:"mediaId"`
	Role    string `json:"role"`
	Sort    int64  `json:"sort"`
	Url     string `json:"url"`
}

type WorkDetailResp struct {
	WorkId        int64           `json:"workId"`
	Type          string          `json:"type"`
	Title         string          `json:"title"`
	Content       string          `json:"content"`
	CoverUrl      string          `json:"coverUrl"`
	DurationMs    int64           `json:"durationMs"`
	VideoPlaylist string          `json:"videoPlaylist,optional"`
	Visibility    string          `json:"visibility"`
	CollectionId  int64           `json:"collectionId,optional"`
	Original      bool            `json:"original"`
	ProcessStatus string          `json:"processStatus"`
	ReviewStatus  string          `json:"reviewStatus"`
	PublishStatus string          `json:"publishStatus"`
	ReviewReason  string          `json:"reviewReason,optional"`
	CreatedAt     string          `json:"createdAt"`
	ScheduledAt   string          `json:"scheduledAt,optional"`
	PublishedAt   string          `json:"publishedAt,optional"`
	Assets        []WorkAssetItem `json:"assets"`
	Topics        []WorkTopicItem `json:"topics"`
}

type WorkIdReq struct {
	WorkId int64 `path:"workId"`
}

type WorkStatusResp struct {
	WorkId        int64  `json:"workId"`
	ProcessStatus string `json:"processStatus"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
	Stage         string `json:"stage"`
	Progress      int64  `json:"progress"`
	Message       string `json:"message"`
	FailureReason string `json:"failureReason"`
	ScheduledAt   string `json:"scheduledAt,optional"`
	PublishedAt   string `json:"publishedAt,optional"`
}

type WorkTopicItem struct {
	TopicId int64  `json:"topicId"`
	Name    string `json:"name"`
}
