// Code generated by goctl. DO NOT EDIT.
package types

type AuditWorkReq struct {
	WorkId   int64  `path:"workId"`
	Decision string `json:"decision"`
	Reason   string `json:"reason,optional"`
}

type AuditWorkResp struct {
	WorkId        int64  `json:"workId"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
}

type CaptchaResp struct {
	CaptchaID   string `json:"captchaId"`
	CaptchaPath string `json:"captchaPath"`
}

type CompleteUploadReq struct {
	MediaId   int64  `json:"mediaId"`
	ObjectKey string `json:"objectKey"`
}

type CompleteUploadResp struct {
	MediaId    int64  `json:"mediaId"`
	Status     string `json:"status"`
	Bucket     string `json:"bucket"`
	ObjectKey  string `json:"objectKey"`
	PreviewUrl string `json:"previewUrl"`
}

type CreateUploadPresignReq struct {
	ResourceType string `json:"resourceType"`
	FileName     string `json:"fileName"`
	ContentType  string `json:"contentType,optional"`
}

type CreateUploadPresignResp struct {
	MediaId    int64             `json:"mediaId"`
	Bucket     string            `json:"bucket"`
	ObjectKey  string            `json:"objectKey"`
	UploadUrl  string            `json:"uploadUrl"`
	PreviewUrl string            `json:"previewUrl"`
	Method     string            `json:"method"`
	ExpiresIn  int64             `json:"expiresIn"`
	Headers    map[string]string `json:"headers"`
}

type CreateWorkReq struct {
	Payload string `form:"payload"`
}

type CreateWorkResp struct {
	WorkId        int64  `json:"workId"`
	ProcessStatus string `json:"processStatus"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
}

type CreatorWorkListItem struct {
	WorkId        int64  `json:"workId"`
	Type          string `json:"type"`
	Title         string `json:"title"`
	CoverUrl      string `json:"coverUrl"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
	ReviewReason  string `json:"reviewReason,optional"`
	ScheduledAt   string `json:"scheduledAt,optional"`
	PublishedAt   string `json:"publishedAt,optional"`
	CreatedAt     string `json:"createdAt"`
}

type CreatorWorkListReq struct {
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"pageSize,optional"`
}

type CreatorWorkListResp struct {
	Total    int64                 `json:"total"`
	Page     int64                 `json:"page"`
	PageSize int64                 `json:"pageSize"`
	List     []CreatorWorkListItem `json:"list"`
}

type LoginReq struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	CaptchaID   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Email            string `json:"email"`
	NickName         string `json:"nickName"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type WorkAssetItem struct {
	MediaId int64  `json:"mediaId"`
	Role    string `json:"role"`
	Sort    int64  `json:"sort"`
	Url     string `json:"url"`
}

type WorkDetailResp struct {
	WorkId        int64           `json:"workId"`
	Type          string          `json:"type"`
	Title         string          `json:"title"`
	Content       string          `json:"content"`
	Visibility    string          `json:"visibility"`
	CollectionId  int64           `json:"collectionId,optional"`
	Original      bool            `json:"original"`
	ProcessStatus string          `json:"processStatus"`
	ReviewStatus  string          `json:"reviewStatus"`
	PublishStatus string          `json:"publishStatus"`
	ScheduledAt   string          `json:"scheduledAt,optional"`
	PublishedAt   string          `json:"publishedAt,optional"`
	Assets        []WorkAssetItem `json:"assets"`
	Topics        []WorkTopicItem `json:"topics"`
}

type WorkIdReq struct {
	WorkId int64 `path:"workId"`
}

type WorkStatusResp struct {
	WorkId        int64  `json:"workId"`
	ProcessStatus string `json:"processStatus"`
	ReviewStatus  string `json:"reviewStatus"`
	PublishStatus string `json:"publishStatus"`
	Stage         string `json:"stage"`
	Progress      int64  `json:"progress"`
	Message       string `json:"message"`
	FailureReason string `json:"failureReason"`
	ScheduledAt   string `json:"scheduledAt,optional"`
	PublishedAt   string `json:"publishedAt,optional"`
}

type WorkTopicItem struct {
	TopicId int64  `json:"topicId"`
	Name    string `json:"name"`
}
