// Code generated by goctl. DO NOT EDIT.
package types

type CaptchaResp struct {
	CaptchaID   string `json:"captchaId"`
	CaptchaPath string `json:"captchaPath"`
}

type LoginReq struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	CaptchaID   string `json:"captchaId"`
	CaptchaCode string `json:"captchaCode"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type RegisterReq struct {
	Emial            string `json:"emial"`
	NickName         string `json:"nickName"`
	Password         string `json:"password"`
	VerificationCode string `json:"verificationCode"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
