// Code generated by goctl. DO NOT EDIT.

package work

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	collectionFieldNames          = builder.RawFieldNames(&Collection{})
	collectionRows                = strings.Join(collectionFieldNames, ",")
	collectionRowsExpectAutoSet   = strings.Join(stringx.Remove(collectionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	collectionRowsWithPlaceHolder = strings.Join(stringx.Remove(collectionFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheCollectionIdPrefix = "cache:collection:id:"
)

type (
	collectionModel interface {
		Insert(ctx context.Context, data *Collection) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Collection, error)
		Update(ctx context.Context, data *Collection) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCollectionModel struct {
		sqlc.CachedConn
		table string
	}

	Collection struct {
		Id        int64        `db:"id"`         // 合集主键ID
		CreatedAt time.Time    `db:"created_at"` // 创建时间
		UpdatedAt time.Time    `db:"updated_at"` // 更新时间
		DeletedAt sql.NullTime `db:"deleted_at"` // 软删除时间
		UserId    int64        `db:"user_id"`    // 合集创建者用户ID
		Name      string       `db:"name"`       // 合集名称
	}
)

func newCollectionModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCollectionModel {
	return &defaultCollectionModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`collection`",
	}
}

func (m *defaultCollectionModel) Delete(ctx context.Context, id int64) error {
	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, collectionIdKey)
	return err
}

func (m *defaultCollectionModel) FindOne(ctx context.Context, id int64) (*Collection, error) {
	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, id)
	var resp Collection
	err := m.QueryRowCtx(ctx, &resp, collectionIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCollectionModel) Insert(ctx context.Context, data *Collection) (sql.Result, error) {
	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, collectionRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.Name)
	}, collectionIdKey)
	return ret, err
}

func (m *defaultCollectionModel) Update(ctx context.Context, data *Collection) error {
	collectionIdKey := fmt.Sprintf("%s%v", cacheCollectionIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, collectionRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.Name, data.Id)
	}, collectionIdKey)
	return err
}

func (m *defaultCollectionModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheCollectionIdPrefix, primary)
}

func (m *defaultCollectionModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", collectionRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCollectionModel) tableName() string {
	return m.table
}
