// Code generated by goctl. DO NOT EDIT.

package work

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	mediaProcessTaskFieldNames          = builder.RawFieldNames(&MediaProcessTask{})
	mediaProcessTaskRows                = strings.Join(mediaProcessTaskFieldNames, ",")
	mediaProcessTaskRowsExpectAutoSet   = strings.Join(stringx.Remove(mediaProcessTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	mediaProcessTaskRowsWithPlaceHolder = strings.Join(stringx.Remove(mediaProcessTaskFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMediaProcessTaskIdPrefix             = "cache:mediaProcessTask:id:"
	cacheMediaProcessTaskWorkIdTaskTypePrefix = "cache:mediaProcessTask:workId:taskType:"
)

type (
	mediaProcessTaskModel interface {
		Insert(ctx context.Context, data *MediaProcessTask) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MediaProcessTask, error)
		FindOneByWorkIdTaskType(ctx context.Context, workId int64, taskType string) (*MediaProcessTask, error)
		Update(ctx context.Context, data *MediaProcessTask) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMediaProcessTaskModel struct {
		sqlc.CachedConn
		table string
	}

	MediaProcessTask struct {
		Id           int64     `db:"id"`            // 媒体处理任务主键ID
		CreatedAt    time.Time `db:"created_at"`    // 创建时间
		UpdatedAt    time.Time `db:"updated_at"`    // 更新时间
		WorkId       int64     `db:"work_id"`       // 待处理作品ID
		TaskType     string    `db:"task_type"`     // 任务类型：process_work处理作品媒体
		Status       string    `db:"status"`        // 任务状态：pending/processing/succeeded/failed
		Stage        string    `db:"stage"`         // 处理阶段：queued/preparing/processing_image/processing_video/waiting_review/failed
		Progress     int64     `db:"progress"`      // 处理进度百分比，范围0到100
		RetryCount   int64     `db:"retry_count"`   // 任务重试次数
		ErrorMessage string    `db:"error_message"` // 最近一次处理失败信息
	}
)

func newMediaProcessTaskModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMediaProcessTaskModel {
	return &defaultMediaProcessTaskModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`media_process_task`",
	}
}

func (m *defaultMediaProcessTaskModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	mediaProcessTaskIdKey := fmt.Sprintf("%s%v", cacheMediaProcessTaskIdPrefix, id)
	mediaProcessTaskWorkIdTaskTypeKey := fmt.Sprintf("%s%v:%v", cacheMediaProcessTaskWorkIdTaskTypePrefix, data.WorkId, data.TaskType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mediaProcessTaskIdKey, mediaProcessTaskWorkIdTaskTypeKey)
	return err
}

func (m *defaultMediaProcessTaskModel) FindOne(ctx context.Context, id int64) (*MediaProcessTask, error) {
	mediaProcessTaskIdKey := fmt.Sprintf("%s%v", cacheMediaProcessTaskIdPrefix, id)
	var resp MediaProcessTask
	err := m.QueryRowCtx(ctx, &resp, mediaProcessTaskIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaProcessTaskRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaProcessTaskModel) FindOneByWorkIdTaskType(ctx context.Context, workId int64, taskType string) (*MediaProcessTask, error) {
	mediaProcessTaskWorkIdTaskTypeKey := fmt.Sprintf("%s%v:%v", cacheMediaProcessTaskWorkIdTaskTypePrefix, workId, taskType)
	var resp MediaProcessTask
	err := m.QueryRowIndexCtx(ctx, &resp, mediaProcessTaskWorkIdTaskTypeKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `work_id` = ? and `task_type` = ? limit 1", mediaProcessTaskRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, workId, taskType); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMediaProcessTaskModel) Insert(ctx context.Context, data *MediaProcessTask) (sql.Result, error) {
	mediaProcessTaskIdKey := fmt.Sprintf("%s%v", cacheMediaProcessTaskIdPrefix, data.Id)
	mediaProcessTaskWorkIdTaskTypeKey := fmt.Sprintf("%s%v:%v", cacheMediaProcessTaskWorkIdTaskTypePrefix, data.WorkId, data.TaskType)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, mediaProcessTaskRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.WorkId, data.TaskType, data.Status, data.Stage, data.Progress, data.RetryCount, data.ErrorMessage)
	}, mediaProcessTaskIdKey, mediaProcessTaskWorkIdTaskTypeKey)
	return ret, err
}

func (m *defaultMediaProcessTaskModel) Update(ctx context.Context, newData *MediaProcessTask) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	mediaProcessTaskIdKey := fmt.Sprintf("%s%v", cacheMediaProcessTaskIdPrefix, data.Id)
	mediaProcessTaskWorkIdTaskTypeKey := fmt.Sprintf("%s%v:%v", cacheMediaProcessTaskWorkIdTaskTypePrefix, data.WorkId, data.TaskType)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, mediaProcessTaskRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.WorkId, newData.TaskType, newData.Status, newData.Stage, newData.Progress, newData.RetryCount, newData.ErrorMessage, newData.Id)
	}, mediaProcessTaskIdKey, mediaProcessTaskWorkIdTaskTypeKey)
	return err
}

func (m *defaultMediaProcessTaskModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMediaProcessTaskIdPrefix, primary)
}

func (m *defaultMediaProcessTaskModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", mediaProcessTaskRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMediaProcessTaskModel) tableName() string {
	return m.table
}
