// Code generated by goctl. DO NOT EDIT.

package work

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	topicFieldNames          = builder.RawFieldNames(&Topic{})
	topicRows                = strings.Join(topicFieldNames, ",")
	topicRowsExpectAutoSet   = strings.Join(stringx.Remove(topicFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	topicRowsWithPlaceHolder = strings.Join(stringx.Remove(topicFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheTopicIdPrefix             = "cache:topic:id:"
	cacheTopicNormalizedNamePrefix = "cache:topic:normalizedName:"
)

type (
	topicModel interface {
		Insert(ctx context.Context, data *Topic) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Topic, error)
		FindOneByNormalizedName(ctx context.Context, normalizedName string) (*Topic, error)
		Update(ctx context.Context, data *Topic) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTopicModel struct {
		sqlc.CachedConn
		table string
	}

	Topic struct {
		Id             int64     `db:"id"`              // 话题主键ID
		CreatedAt      time.Time `db:"created_at"`      // 创建时间
		Name           string    `db:"name"`            // 话题展示名称
		NormalizedName string    `db:"normalized_name"` // 用于去重检索的标准化话题名称
	}
)

func newTopicModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTopicModel {
	return &defaultTopicModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`topic`",
	}
}

func (m *defaultTopicModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	topicIdKey := fmt.Sprintf("%s%v", cacheTopicIdPrefix, id)
	topicNormalizedNameKey := fmt.Sprintf("%s%v", cacheTopicNormalizedNamePrefix, data.NormalizedName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, topicIdKey, topicNormalizedNameKey)
	return err
}

func (m *defaultTopicModel) FindOne(ctx context.Context, id int64) (*Topic, error) {
	topicIdKey := fmt.Sprintf("%s%v", cacheTopicIdPrefix, id)
	var resp Topic
	err := m.QueryRowCtx(ctx, &resp, topicIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", topicRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTopicModel) FindOneByNormalizedName(ctx context.Context, normalizedName string) (*Topic, error) {
	topicNormalizedNameKey := fmt.Sprintf("%s%v", cacheTopicNormalizedNamePrefix, normalizedName)
	var resp Topic
	err := m.QueryRowIndexCtx(ctx, &resp, topicNormalizedNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `normalized_name` = ? limit 1", topicRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, normalizedName); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTopicModel) Insert(ctx context.Context, data *Topic) (sql.Result, error) {
	topicIdKey := fmt.Sprintf("%s%v", cacheTopicIdPrefix, data.Id)
	topicNormalizedNameKey := fmt.Sprintf("%s%v", cacheTopicNormalizedNamePrefix, data.NormalizedName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, topicRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.NormalizedName)
	}, topicIdKey, topicNormalizedNameKey)
	return ret, err
}

func (m *defaultTopicModel) Update(ctx context.Context, newData *Topic) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	topicIdKey := fmt.Sprintf("%s%v", cacheTopicIdPrefix, data.Id)
	topicNormalizedNameKey := fmt.Sprintf("%s%v", cacheTopicNormalizedNamePrefix, data.NormalizedName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, topicRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Name, newData.NormalizedName, newData.Id)
	}, topicIdKey, topicNormalizedNameKey)
	return err
}

func (m *defaultTopicModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheTopicIdPrefix, primary)
}

func (m *defaultTopicModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", topicRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTopicModel) tableName() string {
	return m.table
}
