// Code generated by goctl. DO NOT EDIT.

package work

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workFieldNames          = builder.RawFieldNames(&Work{})
	workRows                = strings.Join(workFieldNames, ",")
	workRowsExpectAutoSet   = strings.Join(stringx.Remove(workFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workRowsWithPlaceHolder = strings.Join(stringx.Remove(workFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWorkIdPrefix                   = "cache:work:id:"
	cacheWorkUserIdIdempotencyKeyPrefix = "cache:work:userId:idempotencyKey:"
)

type (
	workModel interface {
		Insert(ctx context.Context, data *Work) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Work, error)
		FindOneByUserIdIdempotencyKey(ctx context.Context, userId int64, idempotencyKey string) (*Work, error)
		Update(ctx context.Context, data *Work) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWorkModel struct {
		sqlc.CachedConn
		table string
	}

	Work struct {
		Id                int64          `db:"id"`                  // 作品主键ID
		CreatedAt         time.Time      `db:"created_at"`          // 创建时间
		UpdatedAt         time.Time      `db:"updated_at"`          // 更新时间
		DeletedAt         sql.NullTime   `db:"deleted_at"`          // 软删除时间
		UserId            int64          `db:"user_id"`             // 作品作者用户ID
		Type              string         `db:"type"`                // 作品类型：image图片作品、video视频作品
		Title             string         `db:"title"`               // 作品主标题
		Content           string         `db:"content"`             // 作品正文内容
		Visibility        string         `db:"visibility"`          // 可见范围：public/private/mutual/selected/excluded
		VisibilityUserIds sql.NullString `db:"visibility_user_ids"` // 指定可见或排除可见的用户ID列表
		CollectionId      int64          `db:"collection_id"`       // 所属合集ID，0表示未加入合集
		Original          int64          `db:"original"`            // 是否声明原创：0否、1是
		CoverAssetId      int64          `db:"cover_asset_id"`      // 封面媒体素材ID
		ProcessStatus     string         `db:"process_status"`      // 媒体处理状态：pending/processing/succeeded/failed
		ReviewStatus      string         `db:"review_status"`       // 审核状态：waiting_process/pending_review/approved/rejected
		PublishStatus     string         `db:"publish_status"`      // 发布状态：pending/scheduled/published/deleted
		ScheduledAt       sql.NullTime   `db:"scheduled_at"`        // 计划发布时间，空表示审核通过后立即发布
		PublishedAt       sql.NullTime   `db:"published_at"`        // 实际发布时间
		ReviewedBy        int64          `db:"reviewed_by"`         // 审核员用户ID
		ReviewedAt        sql.NullTime   `db:"reviewed_at"`         // 审核完成时间
		ReviewReason      string         `db:"review_reason"`       // 审核意见或拒绝原因
		IdempotencyKey    string         `db:"idempotency_key"`     // 用户维度的发布幂等键
	}
)

func newWorkModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWorkModel {
	return &defaultWorkModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`work`",
	}
}

func (m *defaultWorkModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	workIdKey := fmt.Sprintf("%s%v", cacheWorkIdPrefix, id)
	workUserIdIdempotencyKeyKey := fmt.Sprintf("%s%v:%v", cacheWorkUserIdIdempotencyKeyPrefix, data.UserId, data.IdempotencyKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, workIdKey, workUserIdIdempotencyKeyKey)
	return err
}

func (m *defaultWorkModel) FindOne(ctx context.Context, id int64) (*Work, error) {
	workIdKey := fmt.Sprintf("%s%v", cacheWorkIdPrefix, id)
	var resp Work
	err := m.QueryRowCtx(ctx, &resp, workIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkModel) FindOneByUserIdIdempotencyKey(ctx context.Context, userId int64, idempotencyKey string) (*Work, error) {
	workUserIdIdempotencyKeyKey := fmt.Sprintf("%s%v:%v", cacheWorkUserIdIdempotencyKeyPrefix, userId, idempotencyKey)
	var resp Work
	err := m.QueryRowIndexCtx(ctx, &resp, workUserIdIdempotencyKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `idempotency_key` = ? limit 1", workRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, idempotencyKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkModel) Insert(ctx context.Context, data *Work) (sql.Result, error) {
	workIdKey := fmt.Sprintf("%s%v", cacheWorkIdPrefix, data.Id)
	workUserIdIdempotencyKeyKey := fmt.Sprintf("%s%v:%v", cacheWorkUserIdIdempotencyKeyPrefix, data.UserId, data.IdempotencyKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, workRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.UserId, data.Type, data.Title, data.Content, data.Visibility, data.VisibilityUserIds, data.CollectionId, data.Original, data.CoverAssetId, data.ProcessStatus, data.ReviewStatus, data.PublishStatus, data.ScheduledAt, data.PublishedAt, data.ReviewedBy, data.ReviewedAt, data.ReviewReason, data.IdempotencyKey)
	}, workIdKey, workUserIdIdempotencyKeyKey)
	return ret, err
}

func (m *defaultWorkModel) Update(ctx context.Context, newData *Work) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	workIdKey := fmt.Sprintf("%s%v", cacheWorkIdPrefix, data.Id)
	workUserIdIdempotencyKeyKey := fmt.Sprintf("%s%v:%v", cacheWorkUserIdIdempotencyKeyPrefix, data.UserId, data.IdempotencyKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.DeletedAt, newData.UserId, newData.Type, newData.Title, newData.Content, newData.Visibility, newData.VisibilityUserIds, newData.CollectionId, newData.Original, newData.CoverAssetId, newData.ProcessStatus, newData.ReviewStatus, newData.PublishStatus, newData.ScheduledAt, newData.PublishedAt, newData.ReviewedBy, newData.ReviewedAt, newData.ReviewReason, newData.IdempotencyKey, newData.Id)
	}, workIdKey, workUserIdIdempotencyKeyKey)
	return err
}

func (m *defaultWorkModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWorkIdPrefix, primary)
}

func (m *defaultWorkModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWorkModel) tableName() string {
	return m.table
}
