// Code generated by goctl. DO NOT EDIT.

package work

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workTopicFieldNames          = builder.RawFieldNames(&WorkTopic{})
	workTopicRows                = strings.Join(workTopicFieldNames, ",")
	workTopicRowsExpectAutoSet   = strings.Join(stringx.Remove(workTopicFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workTopicRowsWithPlaceHolder = strings.Join(stringx.Remove(workTopicFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWorkTopicIdPrefix            = "cache:workTopic:id:"
	cacheWorkTopicWorkIdTopicIdPrefix = "cache:workTopic:workId:topicId:"
)

type (
	workTopicModel interface {
		Insert(ctx context.Context, data *WorkTopic) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WorkTopic, error)
		FindOneByWorkIdTopicId(ctx context.Context, workId int64, topicId int64) (*WorkTopic, error)
		Update(ctx context.Context, data *WorkTopic) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWorkTopicModel struct {
		sqlc.CachedConn
		table string
	}

	WorkTopic struct {
		Id        int64     `db:"id"`         // 作品话题关系主键ID
		CreatedAt time.Time `db:"created_at"` // 创建时间
		WorkId    int64     `db:"work_id"`    // 作品ID
		TopicId   int64     `db:"topic_id"`   // 话题ID
		Sort      int64     `db:"sort"`       // 话题展示顺序，从0开始
	}
)

func newWorkTopicModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWorkTopicModel {
	return &defaultWorkTopicModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`work_topic`",
	}
}

func (m *defaultWorkTopicModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	workTopicIdKey := fmt.Sprintf("%s%v", cacheWorkTopicIdPrefix, id)
	workTopicWorkIdTopicIdKey := fmt.Sprintf("%s%v:%v", cacheWorkTopicWorkIdTopicIdPrefix, data.WorkId, data.TopicId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, workTopicIdKey, workTopicWorkIdTopicIdKey)
	return err
}

func (m *defaultWorkTopicModel) FindOne(ctx context.Context, id int64) (*WorkTopic, error) {
	workTopicIdKey := fmt.Sprintf("%s%v", cacheWorkTopicIdPrefix, id)
	var resp WorkTopic
	err := m.QueryRowCtx(ctx, &resp, workTopicIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workTopicRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkTopicModel) FindOneByWorkIdTopicId(ctx context.Context, workId int64, topicId int64) (*WorkTopic, error) {
	workTopicWorkIdTopicIdKey := fmt.Sprintf("%s%v:%v", cacheWorkTopicWorkIdTopicIdPrefix, workId, topicId)
	var resp WorkTopic
	err := m.QueryRowIndexCtx(ctx, &resp, workTopicWorkIdTopicIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `work_id` = ? and `topic_id` = ? limit 1", workTopicRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, workId, topicId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkTopicModel) Insert(ctx context.Context, data *WorkTopic) (sql.Result, error) {
	workTopicIdKey := fmt.Sprintf("%s%v", cacheWorkTopicIdPrefix, data.Id)
	workTopicWorkIdTopicIdKey := fmt.Sprintf("%s%v:%v", cacheWorkTopicWorkIdTopicIdPrefix, data.WorkId, data.TopicId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, workTopicRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.WorkId, data.TopicId, data.Sort)
	}, workTopicIdKey, workTopicWorkIdTopicIdKey)
	return ret, err
}

func (m *defaultWorkTopicModel) Update(ctx context.Context, newData *WorkTopic) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	workTopicIdKey := fmt.Sprintf("%s%v", cacheWorkTopicIdPrefix, data.Id)
	workTopicWorkIdTopicIdKey := fmt.Sprintf("%s%v:%v", cacheWorkTopicWorkIdTopicIdPrefix, data.WorkId, data.TopicId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workTopicRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.WorkId, newData.TopicId, newData.Sort, newData.Id)
	}, workTopicIdKey, workTopicWorkIdTopicIdKey)
	return err
}

func (m *defaultWorkTopicModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWorkTopicIdPrefix, primary)
}

func (m *defaultWorkTopicModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workTopicRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWorkTopicModel) tableName() string {
	return m.table
}
