// Code generated by goctl. DO NOT EDIT.

package work

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	workAssetFieldNames          = builder.RawFieldNames(&WorkAsset{})
	workAssetRows                = strings.Join(workAssetFieldNames, ",")
	workAssetRowsExpectAutoSet   = strings.Join(stringx.Remove(workAssetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	workAssetRowsWithPlaceHolder = strings.Join(stringx.Remove(workAssetFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheWorkAssetIdPrefix                 = "cache:workAsset:id:"
	cacheWorkAssetMediaAssetIdPrefix       = "cache:workAsset:mediaAssetId:"
	cacheWorkAssetWorkIdMediaAssetIdPrefix = "cache:workAsset:workId:mediaAssetId:"
)

type (
	workAssetModel interface {
		Insert(ctx context.Context, data *WorkAsset) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*WorkAsset, error)
		FindOneByMediaAssetId(ctx context.Context, mediaAssetId int64) (*WorkAsset, error)
		FindOneByWorkIdMediaAssetId(ctx context.Context, workId int64, mediaAssetId int64) (*WorkAsset, error)
		Update(ctx context.Context, data *WorkAsset) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWorkAssetModel struct {
		sqlc.CachedConn
		table string
	}

	WorkAsset struct {
		Id           int64     `db:"id"`             // 作品素材关系主键ID
		CreatedAt    time.Time `db:"created_at"`     // 创建时间
		WorkId       int64     `db:"work_id"`        // 作品ID
		MediaAssetId int64     `db:"media_asset_id"` // 媒体素材ID
		Role         string    `db:"role"`           // 素材角色：image图片、video视频、cover封面
		Sort         int64     `db:"sort"`           // 素材展示顺序，从0开始
	}
)

func newWorkAssetModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultWorkAssetModel {
	return &defaultWorkAssetModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`work_asset`",
	}
}

func (m *defaultWorkAssetModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	workAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetIdPrefix, id)
	workAssetMediaAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetMediaAssetIdPrefix, data.MediaAssetId)
	workAssetWorkIdMediaAssetIdKey := fmt.Sprintf("%s%v:%v", cacheWorkAssetWorkIdMediaAssetIdPrefix, data.WorkId, data.MediaAssetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, workAssetIdKey, workAssetMediaAssetIdKey, workAssetWorkIdMediaAssetIdKey)
	return err
}

func (m *defaultWorkAssetModel) FindOne(ctx context.Context, id int64) (*WorkAsset, error) {
	workAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetIdPrefix, id)
	var resp WorkAsset
	err := m.QueryRowCtx(ctx, &resp, workAssetIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workAssetRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkAssetModel) FindOneByMediaAssetId(ctx context.Context, mediaAssetId int64) (*WorkAsset, error) {
	workAssetMediaAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetMediaAssetIdPrefix, mediaAssetId)
	var resp WorkAsset
	err := m.QueryRowIndexCtx(ctx, &resp, workAssetMediaAssetIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `media_asset_id` = ? limit 1", workAssetRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, mediaAssetId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkAssetModel) FindOneByWorkIdMediaAssetId(ctx context.Context, workId int64, mediaAssetId int64) (*WorkAsset, error) {
	workAssetWorkIdMediaAssetIdKey := fmt.Sprintf("%s%v:%v", cacheWorkAssetWorkIdMediaAssetIdPrefix, workId, mediaAssetId)
	var resp WorkAsset
	err := m.QueryRowIndexCtx(ctx, &resp, workAssetWorkIdMediaAssetIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `work_id` = ? and `media_asset_id` = ? limit 1", workAssetRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, workId, mediaAssetId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWorkAssetModel) Insert(ctx context.Context, data *WorkAsset) (sql.Result, error) {
	workAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetIdPrefix, data.Id)
	workAssetMediaAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetMediaAssetIdPrefix, data.MediaAssetId)
	workAssetWorkIdMediaAssetIdKey := fmt.Sprintf("%s%v:%v", cacheWorkAssetWorkIdMediaAssetIdPrefix, data.WorkId, data.MediaAssetId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, workAssetRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.WorkId, data.MediaAssetId, data.Role, data.Sort)
	}, workAssetIdKey, workAssetMediaAssetIdKey, workAssetWorkIdMediaAssetIdKey)
	return ret, err
}

func (m *defaultWorkAssetModel) Update(ctx context.Context, newData *WorkAsset) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	workAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetIdPrefix, data.Id)
	workAssetMediaAssetIdKey := fmt.Sprintf("%s%v", cacheWorkAssetMediaAssetIdPrefix, data.MediaAssetId)
	workAssetWorkIdMediaAssetIdKey := fmt.Sprintf("%s%v:%v", cacheWorkAssetWorkIdMediaAssetIdPrefix, data.WorkId, data.MediaAssetId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, workAssetRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.WorkId, newData.MediaAssetId, newData.Role, newData.Sort, newData.Id)
	}, workAssetIdKey, workAssetMediaAssetIdKey, workAssetWorkIdMediaAssetIdKey)
	return err
}

func (m *defaultWorkAssetModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheWorkAssetIdPrefix, primary)
}

func (m *defaultWorkAssetModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", workAssetRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultWorkAssetModel) tableName() string {
	return m.table
}
